import type { AuthSession } from "../auth/types";
import { localizeKnownAiText } from "../core-ai/aiThaiText";
import { documentSummaryMock } from "./documentSummaryData";
import { buildDocumentDetailHref, parseSummaryMarkdown } from "./documentSummaryHelpers";
import type {
  DocumentDetailResponse,
  DocumentLibraryResponse,
  RecapResponse
} from "./documentSummaryContract";
import type {
  DocumentBreakdownItem,
  DocumentLibraryItem,
  DocumentSummaryDetail,
  DocumentSummaryTopic,
  DocumentSummaryViewModel,
  RelatedDocument
} from "./types";

type DocumentSummaryViewModelInput = {
  dashboard: DocumentLibraryResponse;
  details?: DocumentDetailResponse[];
  recaps?: RecapResponse[];
  selectedDocumentId?: string;
  session: AuthSession;
  timestamp?: Date;
};

const fallbackSummaryMarkers = [
  "Corporate Manual:",
  "Enterprise AI Local Engine",
  "This summary was generated by",
  "The manual covers core operational standards and corporate compliance requirements",
  "Follow all corporate standards and operational regulations.",
  "Obtain proper authorisation before sharing sensitive documents.",
  "Report any security breach or safety hazard to supervisors immediately.",
  "Content metadata matches corporate training manual",
  "corporate training manual visual",
  "Document Image:",
  "No text available to summarize."
];

export const toDocumentSummaryViewModel = ({
  dashboard,
  details = [],
  recaps = [],
  selectedDocumentId,
  session,
  timestamp = new Date()
}: DocumentSummaryViewModelInput): DocumentSummaryViewModel => {
  const uploaderFallback = buildUploaderFallback(session);
  const selectedDocument = selectDocumentForDetail(dashboard, selectedDocumentId);
  const documentDetails = details.map((detail) =>
    toDocumentSummaryDetail({
      dashboard,
      detail,
      recap: recaps.find((recap) => recap.file_id === detail.id),
      uploaderFallback
    })
  );

  return {
    apiEndpoint: documentSummaryMock.apiEndpoint,
    apiResponse: dashboard,
    detailEndpointPattern: documentSummaryMock.detailEndpointPattern,
    documentDetails,
    generatedAtLabel: formatGeneratedAt(timestamp),
    recapEndpointPattern: documentSummaryMock.recapEndpointPattern,
    selectedDocumentId: selectedDocument?.id ?? "",
    workspaceName: buildWorkspaceName(session)
  };
};

export const isDocumentLibraryEmpty = (dashboard: DocumentLibraryResponse) => {
  return dashboard.total_documents === 0 && dashboard.documents.length === 0;
};

export const isBackendFallbackSummary = (value?: string | null) => {
  const normalizedValue = value?.trim();

  if (!normalizedValue) {
    return true;
  }

  return fallbackSummaryMarkers.some((marker) =>
    normalizedValue.toLowerCase().includes(marker.toLowerCase())
  );
};

export const selectDocumentForDetail = (
  dashboard: DocumentLibraryResponse,
  selectedDocumentId?: string
): DocumentLibraryItem | undefined => {
  if (selectedDocumentId) {
    const selectedDocument = dashboard.documents.find((document) => document.id === selectedDocumentId);
    if (selectedDocument) {
      return selectedDocument;
    }
  }

  return (
    dashboard.documents.find((document) => document.status === "ready" && document.summary_available) ??
    dashboard.documents.find((document) => document.status === "ready") ??
    dashboard.documents[0]
  );
};

const toDocumentSummaryDetail = ({
  dashboard,
  detail,
  recap,
  uploaderFallback
}: {
  dashboard: DocumentLibraryResponse;
  detail: DocumentDetailResponse;
  recap?: RecapResponse;
  uploaderFallback: string;
}): DocumentSummaryDetail => {
  const libraryDocument = dashboard.documents.find((document) => document.id === detail.id);
  const rawSummary = detail.summary_markdown ?? recap?.summary_markdown ?? libraryDocument?.summary_markdown ?? "";
  const hasDocumentSummary = !isBackendFallbackSummary(rawSummary);
  const summaryMarkdown = hasDocumentSummary ? localizeKnownAiText(rawSummary) : "";
  const sourcePreview = isBackendFallbackSummary(detail.extracted_text_preview)
    ? ""
    : localizeKnownAiText(detail.extracted_text_preview);
  const sections = parseSummaryMarkdown(summaryMarkdown);

  return {
    canUseAiActions: hasDocumentSummary,
    detailedBreakdown: buildBreakdown(sections, sourcePreview),
    filename: detail.filename,
    generatedAtLabel: formatDocumentGeneratedAt(recap?.generated_at ?? detail.created_at),
    id: detail.id,
    keyTopics: buildKeyTopics(sections),
    relatedDocuments: buildRelatedDocuments(dashboard, detail.id),
    sourcePreview: sourcePreview || undefined,
    summaryMarkdown,
    summaryNotice: hasDocumentSummary
      ? undefined
      : "backend ยังไม่ได้ส่งสรุปที่สร้างจากเนื้อหาเอกสารจริง ระบบจึงปิดการถาม AI และสร้างควิซชั่วคราวเพื่อไม่ให้เข้าใจผิด",
    summaryQuality: hasDocumentSummary ? "document-derived" : "needs-backend-summary",
    uploadedByLabel: `อัปโหลดโดย ${uploaderFallback}`
  };
};

const buildBreakdown = (
  sections: ReturnType<typeof parseSummaryMarkdown>,
  extractedTextPreview: string
): DocumentBreakdownItem[] => {
  if (sections.length > 0) {
    return sections.slice(0, 3).map((section, index) => ({
      body: section.body,
      id: section.id || `breakdown-${index + 1}`,
      title: section.title
    }));
  }

  if (extractedTextPreview) {
    return [{
      body: extractedTextPreview,
      id: "document-preview",
      title: "ตัวอย่างข้อความจากเอกสาร"
    }];
  }

  return [];
};

const buildKeyTopics = (
  sections: ReturnType<typeof parseSummaryMarkdown>
): DocumentSummaryTopic[] => {
  return sections.slice(0, 3).map((section, index) => ({
    confidencePercent: Math.max(80, 96 - index * 4),
    id: `topic-${index + 1}`,
    title: section.title
  }));
};

const buildRelatedDocuments = (
  dashboard: DocumentLibraryResponse,
  selectedDocumentId: string
): RelatedDocument[] => {
  return dashboard.documents
    .filter((document) => document.id !== selectedDocumentId)
    .slice(0, 3)
    .map((document) => ({
      filename: document.filename,
      href: buildDocumentDetailHref(document.id),
      id: document.id,
      status: document.status
    }));
};

const buildUploaderFallback = (session: AuthSession) => {
  return session.user.displayName?.trim() || "คุณ";
};


const buildWorkspaceName = (session: AuthSession) => {
  const displayName = session.user.displayName?.trim();

  if (displayName) {
    return `คลังเอกสารของ ${displayName}`;
  }

  return "คลังเอกสาร AI Tutor";
};

const formatGeneratedAt = (timestamp: Date) => {
  return new Intl.DateTimeFormat("th-TH", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Asia/Bangkok"
  }).format(timestamp);
};

const formatDocumentGeneratedAt = (dateValue: string) => {
  const timestamp = new Date(dateValue);

  if (Number.isNaN(timestamp.getTime())) {
    return "อัปเดตจากระบบ";
  }

  return new Intl.DateTimeFormat("th-TH", {
    dateStyle: "medium",
    timeZone: "Asia/Bangkok"
  }).format(timestamp);
};
