const textReplacements: Array<[RegExp, string]> = [
  [/Corporate Manual:/g, "คู่มือการเรียนรู้:"],
  [/Enterprise AI Local Engine/g, "ระบบ AI Tutor"],
  [/Key Guidelines & Operational Procedures/g, "แนวทางสำคัญและขั้นตอนปฏิบัติ"],
  [/Glossary & Technical Terms/g, "คำศัพท์และคำอธิบาย"],
  [/Standard Operating Procedure/g, "ขั้นตอนปฏิบัติมาตรฐาน"],
  [/Service Level Agreement/g, "ข้อตกลงระดับการให้บริการ"],
  [/Adherence to laws, regulations, and specifications relevant to operations/g, "การปฏิบัติตามกฎหมาย ระเบียบ และข้อกำหนดที่เกี่ยวข้อง"],
  [/\bOverview\b/g, "ภาพรวม"],
  [/\bKey Actions\b/g, "สิ่งที่ควรทำ"],
  [/^Overview$/gim, "ภาพรวม"],
  [/^Key Actions$/gim, "สิ่งที่ควรทำ"],
  [/^Lab Safety$/gim, "ความปลอดภัยในห้องปฏิบัติการ"],
  [/^Incidents$/gim, "เหตุผิดปกติ"],
  [/This summary was generated by the ระบบ AI Tutor\./g, "สรุปนี้สร้างโดยระบบ AI Tutor เพื่อช่วยทบทวนบทเรียน"],
  [/This summary was generated by the Enterprise AI Local Engine\./g, "สรุปนี้สร้างโดยระบบ AI Tutor เพื่อช่วยทบทวนบทเรียน"],
  [
    /The manual covers core operational standards and corporate compliance requirements\./g,
    "เอกสารนี้ครอบคลุมแนวทางสำคัญ มาตรฐานการปฏิบัติ และข้อควรระวังที่ควรทบทวนก่อนนำไปใช้"
  ],
  [/Follow all corporate standards and operational regulations\./g, "ปฏิบัติตามมาตรฐานและขั้นตอนที่เกี่ยวข้องอย่างครบถ้วน"],
  [
    /Obtain proper authorisation before sharing sensitive documents\./g,
    "ขออนุญาตให้ถูกต้องก่อนแชร์เอกสารหรือข้อมูลที่มีความละเอียดอ่อน"
  ],
  [
    /Report any security breach or safety hazard to supervisors immediately\./g,
    "รายงานเหตุด้านความปลอดภัยหรือความเสี่ยงให้ผู้ดูแลทราบทันที"
  ],
  [/Review safety checklist before entering the lab\./g, "ทบทวนรายการความปลอดภัยก่อนเข้าห้องปฏิบัติการ"],
  [/Review the checklist before entering the lab\./g, "ทบทวนรายการตรวจสอบก่อนเข้าห้องปฏิบัติการ"],
  [/Wear goggles before entering the lab\./g, "สวมแว่นตานิรภัยก่อนเข้าห้องปฏิบัติการ"],
  [/Report incidents immediately and notify the trainer\./g, "รายงานเหตุผิดปกติทันทีและแจ้งครูผู้สอน"],
  [/Report incidents immediately\./g, "รายงานเหตุผิดปกติทันที"],
  [/Start with the safety checklist before entering the lab\./g, "เริ่มจากการทบทวนรายการความปลอดภัยก่อนเข้าห้องปฏิบัติการ"],
  [/What should I review first\?/g, "ควรทบทวนอะไรก่อน"],
  [/Unknown query/g, "ไม่พบข้อความคำถาม"],
  [/No response was recorded\./g, "ยังไม่มีคำตอบที่บันทึกไว้"],
  [/Citation text is not available in this history entry\./g, "ไม่มีข้อความอ้างอิงในประวัติรายการนี้"],
  [/Use the matched document section as evidence\./g, "ใช้ส่วนเอกสารที่อ้างอิงได้เป็นหลักฐานประกอบคำตอบ"],
  [/Wear goggles/g, "สวมแว่นตานิรภัย"],
  [/Report incidents/g, "รายงานเหตุผิดปกติ"],
  [/Review the safety checklist/g, "ทบทวนรายการความปลอดภัย"],
  [/Review safety checklist/g, "ทบทวนรายการความปลอดภัย"],
  [/Review the checklist/g, "ทบทวนรายการตรวจสอบ"],
  [/The safety checklist is required before lab work\./g, "ต้องทบทวนรายการความปลอดภัยก่อนเริ่มปฏิบัติการ"],
  [/Checklist review is required\./g, "ต้องทบทวนรายการตรวจสอบก่อนเริ่มงาน"],
  [
    /What should learners review before entering the lab\?/g,
    "ผู้เรียนควรทบทวนอะไรก่อนเข้าห้องปฏิบัติการ"
  ],
  [/Which action is safest before lab work\?/g, "การกระทำใดปลอดภัยที่สุดก่อนเริ่มปฏิบัติการ"],
  [
    /What is the primary action required upon discovering a safety hazard\?/g,
    "เมื่อพบความเสี่ยงด้านความปลอดภัย ควรทำอะไรเป็นอันดับแรก"
  ],
  [
    /What is corporate rule #(\d+) regarding document handling\?/g,
    "ข้อควรปฏิบัติข้อที่ $1 เกี่ยวกับการจัดการเอกสารคืออะไร"
  ],
  [/Ignore it and continue normal duties/g, "ละเลยแล้วทำงานตามปกติต่อไป"],
  [/Report it immediately to the supervisor or Safety Committee/g, "รายงานต่อผู้ดูแลหรือคณะกรรมการความปลอดภัยทันที"],
  [/Fix it yourself without reporting/g, "แก้ไขเองโดยไม่รายงาน"],
  [/Discuss it with coworkers at lunch/g, "นำไปคุยเล่นกับเพื่อนร่วมงาน"],
  [/Skip setup to save time/g, "ข้ามการเตรียมตัวเพื่อประหยัดเวลา"],
  [/Start mixing chemicals/g, "เริ่มผสมสารเคมีทันที"],
  [/Wait until the end/g, "รอจนจบกิจกรรม"],
  [/Ignore the checklist/g, "ละเลยรายการตรวจสอบ"],
  [/Store documents in public folders/g, "เก็บเอกสารไว้ในโฟลเดอร์สาธารณะ"],
  [/Classify and store in the designated tenant directory/g, "จัดประเภทและเก็บไว้ในพื้นที่ที่กำหนด"],
  [/Share immediately with external clients/g, "แชร์ให้บุคคลภายนอกทันที"],
  [/Delete after reading once/g, "ลบทิ้งหลังอ่านครั้งเดียว"],
  [
    /Corporate policy mandates immediate reporting to a supervisor to initiate mitigation procedures\./g,
    "แนวปฏิบัติกำหนดให้รายงานผู้ดูแลทันทีเพื่อเริ่มจัดการความเสี่ยง"
  ],
  [
    /Rule (\d+): proper classification prevents cross-tenant data leakage\./g,
    "ข้อ $1: การจัดประเภทเอกสารอย่างถูกต้องช่วยป้องกันข้อมูลรั่วข้ามพื้นที่"
  ],
  [/Safety Protocol Section/g, "ส่วนแนวปฏิบัติด้านความปลอดภัย"],
  [/Document Administration Policy/g, "นโยบายการจัดการเอกสาร"],
  [/section (\d+)/gi, "ส่วนที่ $1"],
  [/Document Administration/g, "การจัดการเอกสาร"],
  [/Safety Protocol/g, "แนวปฏิบัติด้านความปลอดภัย"],
  [/Question Count/g, "จำนวนคำถาม"],
  [/Estimated Time/g, "เวลาโดยประมาณ"],
  [/Ready Sources/g, "แหล่งข้อมูลพร้อมใช้"],
  [/Grounded Answers/g, "คำตอบอ้างอิง"],
  [/Ready Documents/g, "เอกสารพร้อมถาม"],
  [/History Items/g, "ประวัติสนทนา"],
  [/Documents available for RAG chat/g, "เอกสารที่พร้อมใช้ถาม AI พร้อมอ้างอิง"],
  [/Recent chat turns loaded from Backend/g, "ประวัติสนทนาที่โหลดจากระบบ"],
  [/AI answers that include document citations/g, "คำตอบ AI ที่มีอ้างอิงจากเอกสาร"],
  [/Backend-supported range for AI-generated quizzes/g, "จำนวนคำถามที่ระบบรองรับสำหรับควิซจาก AI"],
  [/Estimated learner completion time/g, "เวลาเฉลี่ยที่ผู้เรียนใช้ทำควิซ"],
  [/Documents ready for quiz generation/g, "เอกสารที่พร้อมสร้างแบบทดสอบ"],
  [/Use scenario-based questions grounded in the selected document\./g, "ใช้คำถามเชิงสถานการณ์จากเอกสารที่เลือก"],
  [/Keep every option clear and distinct\./g, "ตัวเลือกแต่ละข้อควรชัดเจนและแยกกันได้"],
  [/Do not expose answer keys in learner-facing previews\./g, "ไม่แสดงเฉลยในหน้าผู้เรียนก่อนส่งคำตอบ"],
  [/Safety hazard/g, "ความเสี่ยงด้านความปลอดภัย"],
  [/Document handling/g, "การจัดการเอกสาร"],
  [/Unable to answer from the selected document\./g, "ยังตอบจากเอกสารที่เลือกไม่ได้"],
  [/No relevant company document content was found\./g, "ยังไม่พบเนื้อหาที่เกี่ยวข้องในเอกสารที่เลือก"],
  [/Please upload the relevant document first\./g, "กรุณาอัปโหลดหรือเลือกเอกสารที่เกี่ยวข้องก่อน"],
  [/company documents?/gi, "เอกสารที่เลือก"]
];

export const localizeKnownAiText = (value: string) => {
  return textReplacements.reduce((currentValue, [pattern, replacement]) => {
    return currentValue.replace(pattern, replacement);
  }, value);
};
